app:
  host: 127.0.0.1
  port: 6800
  token:
log:
  LogFile: bt-updater.log
  LogWay: console
  LogLevel: info
  LogMaxDays: 0
  DisableLogColor: false
btTrackerUrl: https://cf.trackerslist.com/all_aria2.txt
httpProxy:
frequency: 60
